FROM python:3.8.10

WORKDIR /examples

RUN pip install pandas scikit-learn tensorflow keras

COPY connectors/ /examples/connectors/
COPY examples/Irys_dataset.py /examples/

ENTRYPOINT ["tail", "-f", "/dev/null"]